/-
BOMA N-Core R-B candidate backend payload.

This file REPRESENTS / IMPLEMENTS N-RB-CAND-001 under
BOMA-RB-FORMAL-001. It is not the canonical definition of the
pre-numerical TCT construction, and it does not use Lean's built-in Nat
as the carrier definition.

Formal verification status remains pending until checked by the pinned
repository Lean environment / CI.
-/

namespace BOMA.NCore

universe u

inductive BOMANat where
  | z : BOMANat
  | s : BOMANat → BOMANat

open BOMANat

/-- RB-O01: successor constructor is disjoint from the base constructor. -/
theorem s_ne_z (n : BOMANat) : s n ≠ z := by
  intro h
  cases h

/-- RB-O02: successor constructor is injective. -/
theorem s_injective {a b : BOMANat} (h : s a = s b) : a = b := by
  cases h
  rfl

/-- RB-O04: nondependent recursion/fold over the fresh BOMA carrier. -/
def fold {X : Type u} (x0 : X) (step : X → X) : BOMANat → X
  | z => x0
  | s n => step (fold x0 step n)

@[simp] theorem fold_z {X : Type u} (x0 : X) (step : X → X) :
    fold x0 step z = x0 := rfl

@[simp] theorem fold_s {X : Type u} (x0 : X) (step : X → X) (n : BOMANat) :
    fold x0 step (s n) = step (fold x0 step n) := rfl

/--
RB-O03 / RB-O06 demonstration at the proposition level.
The full dependent eliminator is generated by the inductive declaration;
this theorem records the ordinary proposition-valued induction instance.
-/
theorem induction_adequacy
    (P : BOMANat → Prop)
    (hz : P z)
    (hs : ∀ n, P n → P (s n)) :
    ∀ n, P n := by
  intro n
  induction n with
  | z => exact hz
  | s n ih => exact hs n ih

/--
RB-O05: pointwise uniqueness of recursion.
This deliberately proves pointwise equality and does not assume function
extensionality.
-/
theorem fold_unique
    {X : Type u}
    (x0 : X)
    (step : X → X)
    (h : BOMANat → X)
    (hz : h z = x0)
    (hs : ∀ n, h (s n) = step (h n)) :
    ∀ n, h n = fold x0 step n := by
  intro n
  induction n with
  | z => exact hz
  | s n ih =>
      calc
        h (s n) = step (h n) := hs n
        _ = step (fold x0 step n) := congrArg step ih
        _ = fold x0 step (s n) := by rfl

end BOMA.NCore
