/- Archimedean characterization of the selected Dedekind quotient carrier.
The proof reuses only the certified rational natural-upper-bound contribution;
it does not consume finite cut-membership search or cut-bracketing. -/
namespace BOMA.R.DedekindArchimedean001

open BOMA.NCore.RB001
open BOMA.NCore.RB001.BOMANat
open BOMA.Q.Quotient001
open BOMA.Q.Embedding001
open BOMA.Q.Order001
open BOMA.R.Gateway001
open BOMA.R.QArchimedeanUpperBound001
open BOMA.R.DedekindProbe001
open BOMA.R.DedekindQuotient001
open BOMA.R.DedekindStrictOrder001

/-- Constructive mixed strict/non-strict transitivity used locally so the
Archimedean theorem does not inherit the real-addition payload merely for a Q helper. -/
theorem qlt_le_trans_arch {x y z : QBOMA}
    (hxy : qLT x y) (hyz : qLE y z) : qLT x z := by
  refine ⟨qle_trans hxy.1 hyz, ?_⟩
  intro hxz
  have hyx : qLE y x := by
    have h := hyz
    rw [← hxz] at h
    exact h
  have hxyEq : x = y := qle_antisymm hxy.1 hyx
  exact hxy.2 hxyEq

/-- Every selected lower cut lies strictly below some principal cut generated by
an embedded BOMA natural. -/
theorem cut_strict_below_natural_principal
    (A : LowerCut) :
    ∃ n : BOMANat,
      CutLE A (principalCut (qOfN n)) ∧
      ¬ CutEquiv A (principalCut (qOfN n)) := by
  rcases A.proper with ⟨u, huNotA⟩
  let u1 := qAdd u qOne
  have huu1 : qLT u u1 := by
    have h := qlt_add_right qzero_lt_one u
    change qLT (qAdd qZero u) (qAdd qOne u) at h
    rw [qAdd_zero_left, qAdd_comm qOne u] at h
    exact h
  rcases q_le_natural_upper u1 with ⟨n, hu1n⟩
  have hun : qLT u (qOfN n) := qlt_le_trans_arch huu1 hu1n

  have hLE : CutLE A (principalCut (qOfN n)) := by
    intro a haA
    change qLT a (qOfN n)
    have hau : qLT a u := by
      rcases qle_total a u with hau | hua
      · refine ⟨hau, ?_⟩
        intro heq
        apply huNotA
        rw [← heq]
        exact haA
      · exact False.elim (huNotA (A.downward haA hua))
    exact qlt_trans hau hun

  have hne : ¬ CutEquiv A (principalCut (qOfN n)) := by
    intro hEq
    exact huNotA ((hEq u).2 hun)

  exact ⟨n, hLE, hne⟩

/-- RA-13: every selected real lies strictly below an embedded BOMA natural. -/
theorem r_archimedean_strict_upper (x : RBOMA) :
    ∃ n : BOMANat, rLT x (rOfQ (qOfN n)) := by
  refine Quotient.inductionOn x ?_
  intro A
  rcases cut_strict_below_natural_principal A with ⟨n, hLE, hne⟩
  refine ⟨n, ?_⟩
  change rLT (rmk A) (rmk (principalCut (qOfN n)))
  exact (rlt_mk_iff A (principalCut (qOfN n))).2 ⟨hLE, hne⟩

end BOMA.R.DedekindArchimedean001
